### ISSUE TITLE
Cannot delete criterion (2.1.0 - 0.85)

### ISSUE THREAD

**Issue by tsmr** [InfotelGLPI/typology#1]
on version 2.1.0 (not yet official)

Delete a criterion doesn't work
- from the list of criteria : Operation failed
- from the criterion form itself : Fatal error: Class '' not found in /var/www/glpi085/plugins/typology/inc/typologycriteria.class.php on line 358

**Comment by mathieuchateau** [comment]
I guess this issue can be closed?

**Comment by amma35** [comment]
Fixed in the latest version
