### ISSUE TITLE
Authorization assignment and rules

### ISSUE THREAD

**Issue by raregtp** [InfotelGLPI/typology#17]
Dear GLPi user.

BEFORE SUBMITTING YOUR ISSUE, please make sure to read and follow these steps :

* Verify that your question has not already been asked
* Please use the below template.
* Delete this text before submiting your issue.

The Plugin team.

------------
* Version of the plugin : 2.6.0

* Version of your GLPI : 9.4.0

* Steps to reproduce (which actions have you made) : Install the Typologies plugin, and then as Super-Admin try to create a rule for assigning a typology to a computer under the Rules area in Administration.  The plus is greyed out.  Manually browsing to ruletypology.form.php and filling out the form generates a permissions error when trying to save the form.

Also unable to see the Typologies - Rules for assigning a typology to a computer rule at all for the Admin profile, even after granting full rights.

* Expected result : The ability to create a Typology rule

* Actual result : Not able to create a Typology rule and not able to create typologies that function.

* URL of the page : 

* Screenshot of the problem (if pertinent) :

**Comment by mohamedHD** [comment]
![Capture1](https://user-images.githubusercontent.com/34243898/56143094-d03efc80-5f97-11e9-9369-4651db1a02f0.JPG)

**Comment by keha35** [comment]
Hi,

Is this issue still in progress?

**Comment by raregtp** [comment]
Confirmed resolved.....I can now create typology rules.  Thanks!
