### ISSUE TITLE
Plugin release 2.7.1 don't have release artifact

### ISSUE THREAD

**Issue by AKorezin** [InfotelGLPI/typology#19]
### Version of the plugin : 
2.7.1

### Version of your GLPI : 
9.5.1

### Steps to reproduce (which actions have you made) :
1. Open https://github.com/InfotelGLPI/typology/releases/tag/2.7.1
2. Look for glpi-typology-2.7.1.tar.gz in assets
3. Open link https://github.com/InfotelGLPI/typology/releases/download/2.7.1/glpi-typology-2.7.1.tar.gz

### Expected result :
Link https://github.com/InfotelGLPI/typology/releases/download/2.7.1/glpi-typology-2.7.1.tar.gz returns file, not 404

### Actual result :
1. Link returns 404
2. Build artifact not uploaded

### Additional info
https://github.com/InfotelGLPI/typology/blob/c0344d01ba7aadfb5fadecbfeca319b756af01dc/typology.xml#L31

**Comment by keha35** [comment]
He,

we have desabled the plugin from the marketplace for now.
It will be enabled for the next release.

Br.

**Comment by AKorezin** [comment]
And what about asset for 2.7.1?
Should I use 2.7.0 instead?

**Comment by keha35** [comment]
Use the 2.7.0 version for now.
