### ISSUE TITLE
Sql error in Processor typed criteria

### ISSUE THREAD

**Issue by tsmr** [InfotelGLPI/typology#3]
Create a criteria with element Processors.
Add a definition : field = Name, logical operator = IS, choose any value in the list -> an sql-error is generated

Notice(8): Undefined index: name 
Backtrace : 
/var/www/glpi084/inc/toolbox.class.php:531 Toolbox::userErrorHandlerNormal() 
/var/www/glpi084/inc/dropdown.class.php:300 Toolbox::userErrorHandlerDebug() 
/var/www/glpi084/ajax/comments.php:69 Dropdown::getDropdownName()

https://forge.glpi-project.org/issues/5334

**Comment by mathieuchateau** [comment]
I guess this issue can be closed?

**Comment by amma35** [comment]
Fixed in the latest version
